[versions]
kotlin = "2.4.0"
kotlinx-serialization = "1.11.0"
kotlinx-benchmark = "0.4.16"
quickMpp = "0.22"
equalsTester = "1.1.0"
karamelUtils = "0.2.1"
zeroJson = "0.5.2"

[libraries]
kotlinx-benchmark = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
equalsTester = { module = "io.github.adokky:equals-tester", version.ref = "equalsTester" }
karamelUtils-core = { module = "io.github.adokky:karamel-utils-core", version.ref = "karamelUtils" }
objectPool = { module = "io.github.adokky:object-pool", version = "1.0" }
bitvector = { module = "io.github.adokky:bitvector", version = "0.9.2" }
zeroJson-kotlinx = { module = "io.github.adokky:zero-json-kotlinx", version.ref = "zeroJson" }
zeroJson-core = { module = "io.github.adokky:zero-json-core", version.ref = "zeroJson" }

[plugins]
quick-mpp = { id = "io.github.adokky.quick-mpp", version.ref = "quickMpp" }
quick-publish = { id = "io.github.adokky.quick-publish", version.ref = "quickMpp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }
allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }